services:
  postgres_db_dev:
    image: postgres:16
    container_name: escritr_postgres_dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - escritr_dev_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_DEV}"]
      interval: 10s
      timeout: 5s
      retries: 5

  writing_api:
    image: joaogabrielferr/writing-api
    container_name: escritr_api_dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db_dev:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      postgres_db_dev:
        condition: service_healthy
      localstack:
        condition: service_healthy

    networks:
      - escritr_dev_network
    restart: unless-stopped

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1                #more logs from LocalStack
      - DEFAULT_REGION=us-east-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack" # Persist LocalStack state
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_dev_data:

networks:
  escritr_dev_network:
    driver: bridge
